trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - 'modules/**'

variables: 
- name: ServiceConnectionName
  value: cor-sandbox-espinalg-001
- name: ResourceGroupName
  value: rg-mazneu-cor-a-sandbox-espinalg-001
- name: ModuleName
  value: storage-account
- name: ModuleRegistryServer
  value: registryespinalg001.azurecr.io
- name: ModuleFilePath
  value: ej5/modules/main.bicep
- name: ModuleMetadataFilePath
  value: ej5/modules/main.bicep

pool:
  vmImage: ubuntu-latest

stages:

- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep build --file $(ModuleFilePath)
        name: LintBicepCode
        displayName: Run Bicep linter

- stage: Publish
  jobs:
  - job: Publish
    steps:
      - script: |
          majorMinorVersionNumber=$(jq '(.version.major | tostring) + "." + (.version.minor | tostring)' $(ModuleMetadataFilePath) -r )
          versionNumber="$majorMinorVersionNumber.$(Build.BuildId)"
          echo "##vso[task.setvariable variable=ModuleVersion;]$versionNumber"
        name: GetModuleVersionNumber
        displayName: Get module version number
      - task: AzureCLI@2
        name: Publish
        displayName: Publish module
        inputs:
          azureSubscription: $(ServiceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az bicep publish \
              --target 'br:$(ModuleRegistryServer)/$(ModuleName):$(ModuleVersion)' \
              --file $(ModuleFilePath)