trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

  variables:
    ResourceGroupName: 'rg-mazneu-cor-a-sandbox-espinalg-001'
    ServiceConnectionName: 'cor-sandbox-espinalg-001'

stages:

- stage: Build
  jobs:
  # Build the Visual Studio solution.
  - template: pipeline-templates/build.yml

  # Lint the Bicep file.
  - template: pipeline-templates/lint.yml

# Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Test

# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: Production